# keda Helm chart values for GKE Autopilot
resources:
  operator:
    requests:
      memory: 114Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 500m
  metricsServer:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 200m

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"

# Enable Workload Identity
serviceAccount:
  create: true

rbac:
  create: true

# Enable Prometheus metrics integration
metricsServer:
  enabled: true
  affinity: {}

prometheus:
  createServiceMonitor: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus-operator

