controllerManager:
  replicaCount: 2
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
