controllerManager:
  featureGates:
    # need this feature gate for mixtral-8x7b/nemo-pretraining-gke
    - name: TopologyAwareScheduling
      enabled: true
  replicaCount: 2
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

# GPU Node Pools Configuration
# This will be populated by the ApplicationSet from cluster metadata
gpuNodePools:
  # Comma-separated list of GPU node pool names
  # Example: "gpu-pool-1,gpu-pool-2,ml-gpu-pool"
  pools: ""

  # Enable generation of GPU-specific Kueue resources
  enabled: true

  # Default resource quotas for GPU pools
  defaultQuotas:
    gpu: "1000000000" # "Infinite" quota

  localQueueNamespaces:
    - benchmarks
    - default

# Additional Kueue resources to create
additionalResources:
  enabled: true
